// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForBulkCreateProjetoDetalhesChunks implements pgx.CopyFromSource.
type iteratorForBulkCreateProjetoDetalhesChunks struct {
	rows                 []BulkCreateProjetoDetalhesChunksParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateProjetoDetalhesChunks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateProjetoDetalhesChunks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjetoID,
		r.rows[0].Content,
		r.rows[0].HeaderPath,
		r.rows[0].Ordem,
	}, nil
}

func (r iteratorForBulkCreateProjetoDetalhesChunks) Err() error {
	return nil
}

func (q *Queries) BulkCreateProjetoDetalhesChunks(ctx context.Context, arg []BulkCreateProjetoDetalhesChunksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"projetos_detalhes_chunks"}, []string{"projeto_id", "content", "header_path", "ordem"}, &iteratorForBulkCreateProjetoDetalhesChunks{rows: arg})
}
