// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Projeto struct {
	ID           int32            `json:"id"`
	Nome         string           `json:"nome"`
	CriadoEm     pgtype.Timestamp `json:"criadoEm"`
	DeletadoEm   pgtype.Timestamp `json:"deletadoEm"`
	AtualizadoEm pgtype.Timestamp `json:"atualizadoEm"`
}

type Tarefa struct {
	ID            int32            `json:"id"`
	Numero        int32            `json:"numero"`
	Ano           int32            `json:"ano"`
	Titulo        string           `json:"titulo"`
	Descricao     pgtype.Text      `json:"descricao"`
	ProjetoID     int32            `json:"projetoId"`
	CriadoPorID   int32            `json:"criadoPorId"`
	ResponsavelID int32            `json:"responsavelId"`
	SituacaoID    int32            `json:"situacaoId"`
	TipoID        int32            `json:"tipoId"`
	CriadoEm      pgtype.Timestamp `json:"criadoEm"`
	UltimaMovEm   pgtype.Timestamp `json:"ultimaMovEm"`
	AtualizadoEm  pgtype.Timestamp `json:"atualizadoEm"`
}

type TarefasAnexo struct {
	ID           int32            `json:"id"`
	TarefaID     int32            `json:"tarefaId"`
	Uuid         string           `json:"uuid"`
	Nome         string           `json:"nome"`
	Local        string           `json:"local"`
	Tamanho      pgtype.Int8      `json:"tamanho"`
	CriadoEm     pgtype.Timestamp `json:"criadoEm"`
	AtualizadoEm pgtype.Timestamp `json:"atualizadoEm"`
}

type TarefasMovimentaco struct {
	ID           int32            `json:"id"`
	TarefaID     int32            `json:"tarefaId"`
	SituacaoID   int32            `json:"situacaoId"`
	Descricao    pgtype.Text      `json:"descricao"`
	CriadoPorID  int32            `json:"criadoPorId"`
	CriadoEm     pgtype.Timestamp `json:"criadoEm"`
	AtualizadoEm pgtype.Timestamp `json:"atualizadoEm"`
}

type TarefasSituaco struct {
	ID            int32            `json:"id"`
	Descricao     string           `json:"descricao"`
	EncerraTarefa pgtype.Bool      `json:"encerraTarefa"`
	CriadoEm      pgtype.Timestamp `json:"criadoEm"`
	AtualizadoEm  pgtype.Timestamp `json:"atualizadoEm"`
}

type TarefasTipo struct {
	ID           int32            `json:"id"`
	Descricao    string           `json:"descricao"`
	CriadoEm     pgtype.Timestamp `json:"criadoEm"`
	AtualizadoEm pgtype.Timestamp `json:"atualizadoEm"`
}

type Usuario struct {
	ID           int32            `json:"id"`
	Nome         string           `json:"nome"`
	Email        string           `json:"email"`
	Senha        string           `json:"senha"`
	CriadoEm     pgtype.Timestamp `json:"criadoEm"`
	AtualizadoEm pgtype.Timestamp `json:"atualizadoEm"`
}
