// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Projeto struct {
	ID         int32
	Nome       string
	CriadoEm   pgtype.Timestamp
	DeletadoEm pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Tarefa struct {
	ID            int32
	Numero        int32
	Ano           int32
	Titulo        string
	Descricao     pgtype.Text
	ProjetoID     int32
	CriadoPorID   int32
	ResponsavelID int32
	SituacaoID    int32
	TipoID        int32
	CriadoEm      pgtype.Timestamp
	UltimaMovEm   pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type TarefasAnexo struct {
	ID        int32
	TarefaID  int32
	Uuid      string
	Nome      string
	Local     string
	Tamanho   pgtype.Int8
	CriadoEm  pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TarefasMovimentaco struct {
	ID          int32
	TarefaID    int32
	SituacaoID  int32
	Descricao   pgtype.Text
	CriadoPorID int32
	CriadoEm    pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type TarefasSituaco struct {
	ID            int32
	Descricao     string
	EncerraTarefa pgtype.Bool
	CriadoEm      pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type TarefasTipo struct {
	ID        int32
	Descricao string
	CriadoEm  pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Usuario struct {
	ID        int32
	Nome      string
	Email     string
	Senha     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
