// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Projeto struct {
	ID         int32
	Nome       string
	CriadoEm   pgtype.Timestamp
	DeletadoEm pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Tarefa struct {
	ID            int32
	Numero        int32
	Ano           int32
	Descricao     pgtype.Text
	CriadoPorID   int32
	ResponsavelID int32
	SituacaoID    int32
	TipoID        int32
	CriadoEm      pgtype.Timestamp
	UltimaMovEm   pgtype.Timestamp
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type TarefasAnexo struct {
	ID        int32
	TarefaID  int32
	Nome      string
	Local     pgtype.Text
	Descricao pgtype.Text
	CriadoEm  pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TarefasSituaco struct {
	ID        int32
	Descricao string
	CriadoEm  pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TarefasTipo struct {
	ID        int32
	Descricao string
	CriadoEm  pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Usuario struct {
	ID        int32
	Nome      string
	Senha     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
