// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

)

const getProjeto = `-- name: GetProjeto :one
SELECT id, nome, criado_em, deletado_em, created_at, updated_at FROM projetos
WHERE id = $1 limit 1
`

func (q *Queries) GetProjeto(ctx context.Context, id int32) (Projeto, error) {
	row := q.db.QueryRow(ctx, getProjeto, id)
	var i Projeto
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.CriadoEm,
		&i.DeletadoEm,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
